version: '3.9'
services:
  db:
    container_name: db
    image: 'postgres:14.1-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=my_pgdb
    ports:
      - "5433:5432"

    restart: unless-stopped

  client-backend:
    container_name: backend
    image: docker-spring-boot-postgres:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/my_pgdb
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=1
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update




