server:
  port: 0

# (Data source)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_pgdb
    username: aleks
    password: 3220



# Hibernate
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create


# HTTP PUT, PATCH, DELETE.
#spring.mvc.hiddenmethod.filter.enabled=true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  application:
    name: petproject

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
      distribution:
        percentiles-histogram:
          "[http.server.requests]": true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true